language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
before_script:
  - composer install
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo 'date.timezone = "Europe/Moscow"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ $TRAVIS_PHP_VERSION = 'hhvm' ]]; then echo 'date.timezone = "Etc/GMT-3"' >> /etc/hhvm/php.ini; fi
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar --no-check-certificate
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != 'nightly' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
